#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_DIR="$(cd "$SESSION_DIR/.." && pwd)"
DEFAULT_BASE_ENV="$SESSION_DIR/config/rpc_armv8.phytium_pi.2026-03-01.env"

usage() {
  cat <<'EOF'
Usage:
  prepare_round_env.sh --base-env <path> [--output <path>] [--run-tag <tag>] [--quiet]

Notes:
  - 复制 base env，并注入唯一轮次变量：
    EXECUTION_ID / FULL_EXECUTION_ID / DAILY_REPORT_FILE
  - 默认输出文件：<base>.run_<YYYYmmdd_HHMMSS>.env
  - stdout 仅输出“生成后的 env 绝对路径”，方便被其他脚本调用。
EOF
}

BASE_ENV="$DEFAULT_BASE_ENV"
OUTPUT_ENV=""
RUN_TAG=""
QUIET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-env)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --base-env requires a file path." >&2
        exit 1
      fi
      BASE_ENV="$2"
      shift 2
      ;;
    --output)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --output requires a file path." >&2
        exit 1
      fi
      OUTPUT_ENV="$2"
      shift 2
      ;;
    --run-tag)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --run-tag requires a value." >&2
        exit 1
      fi
      RUN_TAG="$2"
      shift 2
      ;;
    --quiet)
      QUIET=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

resolve_path() {
  local maybe_relative="$1"
  if [[ "$maybe_relative" = /* ]]; then
    printf '%s\n' "$maybe_relative"
  else
    printf '%s\n' "$PROJECT_DIR/$maybe_relative"
  fi
}

sanitize_token() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//'
}

strip_timestamp_suffix() {
  printf '%s' "$1" | sed -E 's/_[0-9]{8}_[0-9]{6}$//'
}

if [[ ! -f "$(resolve_path "$BASE_ENV")" ]]; then
  echo "ERROR: base env not found: $BASE_ENV" >&2
  exit 1
fi
BASE_ENV_RESOLVED="$(resolve_path "$BASE_ENV")"

# shellcheck source=/dev/null
set -a
source "$BASE_ENV_RESOLVED"
set +a

STAMP="$(date +%Y%m%d_%H%M%S)"
DATE_ONLY="$(date +%F)"

if [[ -z "$RUN_TAG" ]]; then
  RUN_TAG="${PROJECT_NAME:-rpc_armv8_round}"
fi
RUN_TAG="$(sanitize_token "$RUN_TAG")"
if [[ -z "$RUN_TAG" ]]; then
  RUN_TAG="rpc_armv8_round"
fi

EXISTING_QUICK_PREFIX="$(strip_timestamp_suffix "${EXECUTION_ID:-}")"
EXISTING_FULL_PREFIX="$(strip_timestamp_suffix "${FULL_EXECUTION_ID:-}")"
if [[ -z "$EXISTING_QUICK_PREFIX" ]]; then
  EXISTING_QUICK_PREFIX="quick_${RUN_TAG}"
fi
if [[ -z "$EXISTING_FULL_PREFIX" ]]; then
  EXISTING_FULL_PREFIX="full_${RUN_TAG}"
fi

DAILY_PATH_BASE="${DAILY_REPORT_FILE:-./session_bootstrap/reports/daily_${RUN_TAG}.md}"
DAILY_DIR="$(dirname "$DAILY_PATH_BASE")"
DAILY_BASENAME="$(basename "$DAILY_PATH_BASE")"
DAILY_BASENAME_NO_EXT="${DAILY_BASENAME%.md}"
DAILY_PREFIX="$(strip_timestamp_suffix "$DAILY_BASENAME_NO_EXT")"
if [[ -z "$DAILY_PREFIX" ]]; then
  DAILY_PREFIX="daily_${RUN_TAG}"
fi

NEXT_EXECUTION_ID="${EXISTING_QUICK_PREFIX}_${STAMP}"
NEXT_FULL_EXECUTION_ID="${EXISTING_FULL_PREFIX}_${STAMP}"
NEXT_DAILY_REPORT_FILE="${DAILY_DIR}/${DAILY_PREFIX}_${STAMP}.md"

if [[ -z "$OUTPUT_ENV" ]]; then
  base_name="$(basename "$BASE_ENV_RESOLVED")"
  base_name="${base_name%.env}"
  OUTPUT_ENV="$(dirname "$BASE_ENV_RESOLVED")/${base_name}.run_${STAMP}.env"
else
  OUTPUT_ENV="$(resolve_path "$OUTPUT_ENV")"
fi

mkdir -p "$(dirname "$OUTPUT_ENV")"

awk '
  !/^EXECUTION_ID=/ &&
  !/^FULL_EXECUTION_ID=/ &&
  !/^DAILY_REPORT_FILE=/
' "$BASE_ENV_RESOLVED" >"$OUTPUT_ENV"

{
  echo
  echo "# generated by prepare_round_env.sh at $(date -Iseconds)"
  echo "EXECUTION_ID=${NEXT_EXECUTION_ID}"
  echo "FULL_EXECUTION_ID=${NEXT_FULL_EXECUTION_ID}"
  echo "DAILY_REPORT_FILE=${NEXT_DAILY_REPORT_FILE}"
  # 兼容 daily 汇总默认日期
  echo "DAILY_REPORT_DATE=${DATE_ONLY}"
} >>"$OUTPUT_ENV"

if [[ "$QUIET" -ne 1 ]]; then
  {
    echo "[prepared] base_env=${BASE_ENV_RESOLVED}"
    echo "[prepared] output_env=${OUTPUT_ENV}"
    echo "[prepared] EXECUTION_ID=${NEXT_EXECUTION_ID}"
    echo "[prepared] FULL_EXECUTION_ID=${NEXT_FULL_EXECUTION_ID}"
    echo "[prepared] DAILY_REPORT_FILE=${NEXT_DAILY_REPORT_FILE}"
  } >&2
fi

printf '%s\n' "$OUTPUT_ENV"
