#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_DIR="$(cd "$SESSION_DIR/.." && pwd)"
DEFAULT_ENV_FILE="$SESSION_DIR/config/local.env"

usage() {
  cat <<'EOF'
Usage:
  rerun_quick_after_ssh_recovery.sh --env <path> [--prefix <execution_prefix>] [--ssh-timeout-sec <n>]

Env used:
  REMOTE_HOST, REMOTE_USER, REMOTE_PASS, optional REMOTE_SSH_PORT (default 22)

What it does:
  1. Probe remote SSH once.
  2. If reachable, create a fresh env snapshot with a new EXECUTION_ID.
  3. Run quick validation.
  4. Regenerate a day-scoped daily summary into a dedicated report file.

Notes:
  - This is a one-shot helper. It does NOT poll/wait in a loop.
  - It refuses to overwrite old quick artifacts by using a new timestamped EXECUTION_ID.
EOF
}

ENV_FILE="$DEFAULT_ENV_FILE"
EXEC_PREFIX="quick_rpc_recheck"
SSH_TIMEOUT_SEC=12

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      ENV_FILE="${2:-}"
      shift 2
      ;;
    --prefix)
      EXEC_PREFIX="${2:-}"
      shift 2
      ;;
    --ssh-timeout-sec)
      SSH_TIMEOUT_SEC="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: env file not found: $ENV_FILE" >&2
  exit 1
fi

if ! [[ "$SSH_TIMEOUT_SEC" =~ ^[0-9]+$ ]] || [[ "$SSH_TIMEOUT_SEC" -lt 1 ]]; then
  echo "ERROR: --ssh-timeout-sec must be a positive integer." >&2
  exit 1
fi

# shellcheck source=/dev/null
set -a
source "$ENV_FILE"
set +a

require_var() {
  local var_name="$1"
  if [[ -z "${!var_name:-}" ]]; then
    echo "ERROR: Missing required variable: $var_name" >&2
    exit 1
  fi
}

resolve_path() {
  local maybe_relative="$1"
  if [[ "$maybe_relative" = /* ]]; then
    printf '%s\n' "$maybe_relative"
  else
    printf '%s\n' "$PROJECT_DIR/$maybe_relative"
  fi
}

for req in REMOTE_HOST REMOTE_USER REMOTE_PASS; do
  require_var "$req"
done
REMOTE_SSH_PORT="${REMOTE_SSH_PORT:-22}"

STAMP="$(date +%Y%m%d_%H%M%S)"
RUN_ENV_DIR="$(resolve_path "./session_bootstrap/tmp/recheck_envs")"
REPORT_DIR_RESOLVED="$(resolve_path "${REPORT_DIR:-./session_bootstrap/reports}")"
mkdir -p "$RUN_ENV_DIR" "$REPORT_DIR_RESOLVED"

RUN_ENV="$RUN_ENV_DIR/${EXEC_PREFIX}_${STAMP}.env"
DAILY_OUTPUT="$REPORT_DIR_RESOLVED/daily_${EXEC_PREFIX}_${STAMP}.md"
EXECUTION_ID_VALUE="${EXEC_PREFIX}_${STAMP}"

set +e
timeout "$SSH_TIMEOUT_SEC" bash "$SCRIPT_DIR/ssh_with_password.sh" \
  --host "$REMOTE_HOST" \
  --user "$REMOTE_USER" \
  --pass "$REMOTE_PASS" \
  --port "$REMOTE_SSH_PORT" \
  -- 'echo SSH_OK && hostname && date -Iseconds'
probe_rc=$?
set -e
if [[ "$probe_rc" -ne 0 ]]; then
  echo "SSH probe failed; remote is still unavailable."
  echo "  host: $REMOTE_HOST"
  echo "  rc:   $probe_rc"
  exit "$probe_rc"
fi

cp "$ENV_FILE" "$RUN_ENV"
{
  echo
  echo "# --- Auto-generated by rerun_quick_after_ssh_recovery.sh (${STAMP}) ---"
  echo "EXECUTION_ID=${EXECUTION_ID_VALUE}"
  echo "DAILY_REPORT_FILE=${DAILY_OUTPUT}"
  echo "DAILY_REPORT_DATE=$(date +%F)"
  echo "ALLOW_REPORT_OVERWRITE=0"
} >>"$RUN_ENV"

bash "$SCRIPT_DIR/run_quick.sh" --env "$RUN_ENV"
bash "$SCRIPT_DIR/summarize_to_daily.sh" --env "$RUN_ENV" --date "$(date +%F)" --output "$DAILY_OUTPUT"

echo "Recheck completed"
echo "  run_env:      $RUN_ENV"
echo "  quick_report: $REPORT_DIR_RESOLVED/${EXECUTION_ID_VALUE}.md"
echo "  daily_report: $DAILY_OUTPUT"
