#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PARENT_SCRIPT="$SCRIPT_DIR/run_phytium_baseline_seeded_warm_start_current_incremental.sh"
DEFAULT_BASE_ENV="$SESSION_DIR/config/rpc_tune_current_safe.baseline_seeded_warm_start.runtime_shifted_top3_targeted.recommended_cortex_a72_neon.2026-03-30.phytium_pi.env"
DEFAULT_INFERENCE_ENV="$SESSION_DIR/config/inference_tvm310_safe.2026-03-10.phytium_pi.env"
RUNTIME_SHIFTED_SOURCE_REPORT="./session_bootstrap/reports/profiling_runtime_top2_tuned_artifact_reprobe_20260330_2055.md"
RUNTIME_SHIFTED_OP_NAMES="fused_conv2d_transpose_add6,fused_conv2d3_add15,fused_conv2d2_add2"

usage() {
  cat <<EOF
Usage:
  bash ./session_bootstrap/scripts/run_phytium_runtime_shifted_top3_targeted_search.sh [options]

Purpose:
  Execute the runtime-shifted-top3 targeted warm-start current tuning flow for Phytium Pi:
    1) lock the next-round target list from ${RUNTIME_SHIFTED_SOURCE_REPORT}
    2) pin TUNE_OP_NAMES to ${RUNTIME_SHIFTED_OP_NAMES}
    3) reuse the existing baseline-seeded incremental wrapper
    4) validate the tuned artifact through the same safe-runtime inference path

Defaults:
  base rebuild env : $DEFAULT_BASE_ENV
  inference env    : $DEFAULT_INFERENCE_ENV
  shifted-top3 ops : $RUNTIME_SHIFTED_OP_NAMES
  report prefix    : phytium_runtime_shifted_top3_targeted_search_<timestamp>

Options:
  All options supported by run_phytium_baseline_seeded_warm_start_current_incremental.sh
  are forwarded as-is, except --rebuild-env which is treated as the base env for
  the generated runtime-shifted-top3 overlay.

Notes:
  - This wrapper exists because the runtime-top2 run proved the original two deconv hotspots
    can be reduced locally, but the integrated artifact shifted the end-to-end bottleneck.
  - The wrapper generates a temporary env overlay so the shifted-top3 op list stays pinned.
EOF
}

require_file() {
  local path="$1"
  local label="$2"
  if [[ ! -f "$path" ]]; then
    echo "ERROR: ${label} not found: $path" >&2
    exit 1
  fi
}

BASE_ENV="$DEFAULT_BASE_ENV"
FORWARD_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --rebuild-env)
      BASE_ENV="${2:-}"
      if [[ -z "$BASE_ENV" ]]; then
        echo "ERROR: --rebuild-env requires a file path." >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      FORWARD_ARGS+=("$1")
      shift
      ;;
  esac
done

require_file "$PARENT_SCRIPT" "baseline-seeded incremental wrapper"
require_file "$BASE_ENV" "runtime-shifted-top3 base env"
require_file "$DEFAULT_INFERENCE_ENV" "default inference env"

mkdir -p "$SESSION_DIR/tmp"
OVERLAY_ENV="$(mktemp "$SESSION_DIR/tmp/runtime_shifted_top3_targeted_overlay_XXXXXX.env")"
trap 'rm -f "$OVERLAY_ENV"' EXIT

cat >"$OVERLAY_ENV" <<EOF
# Auto-generated by run_phytium_runtime_shifted_top3_targeted_search.sh.
# shellcheck source=/dev/null
source "$BASE_ENV"
RUNTIME_HOTSPOT_SOURCE_REPORT=${RUNTIME_SHIFTED_SOURCE_REPORT}
TUNE_OP_NAMES=${RUNTIME_SHIFTED_OP_NAMES}
TUNE_MAX_TRIALS_PER_TASK=160
TUNE_MODE_LABEL=baseline_seeded_warm_start_current_safe_runtime_shifted_top3_targeted_cortex_a72_neon
EOF

DEFAULT_REPORT_ID="phytium_runtime_shifted_top3_targeted_search_$(date +%Y%m%d_%H%M%S)"

exec bash "$PARENT_SCRIPT" \
  --rebuild-env "$OVERLAY_ENV" \
  --inference-env "$DEFAULT_INFERENCE_ENV" \
  --report-id "$DEFAULT_REPORT_ID" \
  "${FORWARD_ARGS[@]}"
