#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PARENT_SCRIPT="$SCRIPT_DIR/run_phytium_current_safe_staging_validate.sh"
DEFAULT_BASE_ENV="$SESSION_DIR/config/rpc_tune_current_safe.baseline_seeded_warm_start.runtime_joint_top6_targeted.recommended_cortex_a72_neon.2026-03-30.phytium_pi.env"
DEFAULT_INFERENCE_ENV="$SESSION_DIR/config/inference_tvm310_safe.2026-03-10.phytium_pi.env"
DEFAULT_STAGING_REMOTE_ARCHIVE="/home/user/Downloads/jscc-test/jscc_staging"
RUNTIME_JOINT_SOURCE_REPORT="./session_bootstrap/reports/profiling_runtime_joint_top5_staging_artifact_reprobe_fixed_20260330_2305.md"
RUNTIME_JOINT_OP_NAMES="fused_conv2d_add2,fused_conv2d_transpose2_add12,fused_conv2d_transpose1_add9,fused_conv2d_transpose_add6,fused_conv2d3_add15,fused_conv2d2_add2"

usage() {
  cat <<EOF
Usage:
  bash ./session_bootstrap/scripts/run_phytium_runtime_joint_top6_targeted_staging_search.sh [options]

Purpose:
  Execute a conservative joint-top6 targeted warm-start current tuning flow for Phytium Pi,
  validated only in a remote staging archive before any promotion decision.

Defaults:
  base rebuild env   : $DEFAULT_BASE_ENV
  inference env      : $DEFAULT_INFERENCE_ENV
  staging archive    : $DEFAULT_STAGING_REMOTE_ARCHIVE
  joint-top6 ops     : $RUNTIME_JOINT_OP_NAMES
  report prefix      : phytium_runtime_joint_top6_targeted_staging_search_<timestamp>

Options:
  All options supported by run_phytium_current_safe_staging_validate.sh are forwarded as-is,
  except --rebuild-env which is treated as the base env for the generated joint-top6 overlay.

Notes:
  - This wrapper extends joint-top5 with the new reprobe top-1 fused_conv2d_add2.
  - The run stays in staging, so even a bad candidate will not overwrite trusted current.
EOF
}

require_file() {
  local path="$1"
  local label="$2"
  if [[ ! -f "$path" ]]; then
    echo "ERROR: ${label} not found: $path" >&2
    exit 1
  fi
}

BASE_ENV="$DEFAULT_BASE_ENV"
FORWARD_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --rebuild-env)
      BASE_ENV="${2:-}"
      if [[ -z "$BASE_ENV" ]]; then
        echo "ERROR: --rebuild-env requires a file path." >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      FORWARD_ARGS+=("$1")
      shift
      ;;
  esac
done

require_file "$PARENT_SCRIPT" "current-safe staging validate wrapper"
require_file "$BASE_ENV" "runtime-joint-top6 base env"
require_file "$DEFAULT_INFERENCE_ENV" "default inference env"

mkdir -p "$SESSION_DIR/tmp"
OVERLAY_ENV="$(mktemp "$SESSION_DIR/tmp/runtime_joint_top6_targeted_overlay_XXXXXX.env")"
trap 'rm -f "$OVERLAY_ENV"' EXIT

cat >"$OVERLAY_ENV" <<EOF
# Auto-generated by run_phytium_runtime_joint_top6_targeted_staging_search.sh.
# shellcheck source=/dev/null
source "$BASE_ENV"
RUNTIME_HOTSPOT_SOURCE_REPORT=${RUNTIME_JOINT_SOURCE_REPORT}
TUNE_OP_NAMES=${RUNTIME_JOINT_OP_NAMES}
TUNE_MAX_TRIALS_PER_TASK=84
TUNE_MODE_LABEL=baseline_seeded_warm_start_current_safe_runtime_joint_top6_targeted_cortex_a72_neon
EOF

DEFAULT_REPORT_ID="phytium_runtime_joint_top6_targeted_staging_search_$(date +%Y%m%d_%H%M%S)"

exec bash "$PARENT_SCRIPT" \
  --rebuild-env "$OVERLAY_ENV" \
  --inference-env "$DEFAULT_INFERENCE_ENV" \
  --remote-archive-dir "$DEFAULT_STAGING_REMOTE_ARCHIVE" \
  --report-id "$DEFAULT_REPORT_ID" \
  "${FORWARD_ARGS[@]}"
